import { Clapperboard, Music, GalleryVerticalEnd, Sparkles, Wand2, MonitorPlay } from "lucide-react";

export default function DreamHunterCeremony() {
    return (
        <section className="w-full py-24 px-8 border-t border-stone-800/30 bg-neutral-900/30 relative overflow-hidden">
            <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-5 pointer-events-none mix-blend-overlay" />

            <div className="max-w-7xl mx-auto relative z-10">
                {/* Header */}
                <div className="text-center space-y-6 mb-20">
                    <span className="block text-xs font-bold tracking-[0.2em] uppercase text-amber-500/80">
                        The World's First
                    </span>
                    <h2 className="text-3xl md:text-5xl font-serif italic text-transparent bg-clip-text bg-gradient-to-br from-stone-100 via-stone-200 to-stone-500">
                        V. Dream Hunter Creation Ceremony
                    </h2>
                    <div className="flex items-center justify-center gap-3 text-stone-400 font-light tracking-wide">
                        <Clapperboard className="w-5 h-5 text-amber-500/80" />
                        <span>AI × Art Fully Support</span>
                    </div>
                </div>

                {/* Content */}
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-20">
                    {/* Item 1: Art */}
                    <div className="readable-panel group p-10 rounded-xl hover:bg-stone-900/60 transition-colors duration-500 border border-stone-800/40 text-center space-y-6">
                        <div className="w-12 h-12 mx-auto rounded-full bg-stone-800/50 flex items-center justify-center border border-stone-700/50 group-hover:border-purple-500/30 group-hover:bg-purple-900/10 transition-all duration-500">
                            <Wand2 className="w-5 h-5 text-stone-300 group-hover:text-purple-300 transition-colors" />
                        </div>
                        <h3 className="text-xl font-serif text-stone-100">Personal Dream<br />Digital Artwork</h3>
                        <ul className="text-stone-400 text-sm space-y-3 leading-relaxed">
                            <li className="flex items-center justify-center gap-2">
                                <span className="w-1 h-1 rounded-full bg-stone-600" />
                                Dream Visual Universe
                            </li>
                            <li className="flex items-center justify-center gap-2">
                                <span className="w-1 h-1 rounded-full bg-stone-600" />
                                Specific chromatogram & energy structure
                            </li>
                            <li className="flex items-center justify-center gap-2">
                                <span className="w-1 h-1 rounded-full bg-stone-600" />
                                Dream symbolic totems
                            </li>
                        </ul>
                    </div>

                    {/* Item 2: Music */}
                    <div className="readable-panel group p-10 rounded-xl hover:bg-stone-900/60 transition-colors duration-500 border border-stone-800/40 text-center space-y-6">
                        <div className="w-12 h-12 mx-auto rounded-full bg-stone-800/50 flex items-center justify-center border border-stone-700/50 group-hover:border-amber-500/30 group-hover:bg-amber-900/10 transition-all duration-500">
                            <Music className="w-5 h-5 text-stone-300 group-hover:text-amber-300 transition-colors" />
                        </div>
                        <h3 className="text-xl font-serif text-stone-100">Custom Music<br />(Sound as Memory)</h3>
                        <ul className="text-stone-400 text-sm space-y-3 leading-relaxed">
                            <li className="flex items-center justify-center gap-2">
                                <span className="w-1 h-1 rounded-full bg-stone-600" />
                                Generated by its dream rhythm
                            </li>
                            <li className="flex items-center justify-center gap-2">
                                <span className="w-1 h-1 rounded-full bg-stone-600" />
                                Can be used for meditation / review / sharing
                            </li>
                        </ul>
                    </div>

                    {/* Item 3: Gallery */}
                    <div className="readable-panel group p-10 rounded-xl hover:bg-stone-900/60 transition-colors duration-500 border border-stone-800/40 text-center space-y-6">
                        <div className="w-12 h-12 mx-auto rounded-full bg-stone-800/50 flex items-center justify-center border border-stone-700/50 group-hover:border-cyan-500/30 group-hover:bg-cyan-900/10 transition-all duration-500">
                            <GalleryVerticalEnd className="w-5 h-5 text-stone-300 group-hover:text-cyan-300 transition-colors" />
                        </div>
                        <h3 className="text-xl font-serif text-stone-100">Virtual Dream Gallery<br />(Virtual Cinematic Exhibition)</h3>
                        <ul className="text-stone-400 text-sm space-y-3 leading-relaxed">
                            <li className="flex items-center justify-center gap-2">
                                <span className="w-1 h-1 rounded-full bg-stone-600" />
                                [Dreamer's Inner Light]
                            </li>
                            <li className="flex items-center justify-center gap-2">
                                <span className="w-1 h-1 rounded-full bg-stone-600" />
                                Each dream represents a unique room
                            </li>
                            <li className="flex items-center justify-center gap-2">
                                <span className="w-1 h-1 rounded-full bg-stone-600" />
                                Globally accessible
                            </li>
                        </ul>
                    </div>
                </div>

                {/* Footer Quote */}
                <div className="text-center">
                    <p className="text-lg md:text-xl font-serif italic text-stone-500/80 tracking-wide">
                        "Every dream exists as an intellectual property in its unique sphere!"
                    </p>
                </div>
            </div>
        </section>
    );
}
